name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_stars: yes
          plugin_gists: yes
          plugin_lines: yes
          plugin_projects: yes
          plugin_music: yes
          plugin_music_provider: "spotify"
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          
          
